- title: true
- shields:
    style: 'flat-square'
    shields:
      - alt: 'Four Kitchens'
        image: 'badge/4K-Four%20Kitchens-35AA4E.svg'
        link: 'https://fourkitchens.com/'
      - alt: 'Travis'
        image: 'travis/fourkitchens/scrummy-server.svg'
        link: 'https://travis-ci.org/fourkitchens/scrummy-server/'
      - alt: Codecov
        image: 'codecov/c/github/fourkitchens/scrummy-server.svg'
        link: 'https://codecov.io/gh/fourkitchens/scrummy-server'
      - alt: Code Climate
        image: 'codeclimate/github/fourkitchens/scrummy-server.svg'
        link: 'https://codeclimate.com/github/fourkitchens/scrummy-server'
      - alt: David Dependency Management
        image: 'david/fourkitchens/scrummy-server.svg'
        link: 'https://david-dm.org/fourkitchens/scrummy-server'
      - alt: David Dependency Management (dev)
        image: 'david/dev/fourkitchens/scrummy-server.svg'
        link: 'https://david-dm.org/dev/fourkitchens/scrummy-server#info=devDependencies&view=table'
- include: './docs/getting-started.md'
- include: './docs/testing.md'
- include: './docs/usage.md'
- jsdoc: 'app.js'
- contributors: true
- license: true
