language: node_js
node_js: 6.0.0
install: npm i
script:
- npm t
- npm run lint-code
- npm run lint-writing
after_success:
- npm run coverage
- npm run quality
addons:
  code_climate:
    repo_token:
      secure: SdHeiYPxcIHdEDOridzOguNGQU7djQ3lAI987ic7nrCOzox976Z/wkqRK8gvmIrn4g6ZpuSIRAAWCJ79ENQm2b3rKFOh5miF3Dl1lTKRZfxwAQnS8lneacUHCjtkHmoJOhkpx1yVVxTyIuWXv56M+SRvTje+3Se0pdTtDBvFvuTOLRPALyVKkSI31PCexBgAi2jzIcXtst6fUgxIx/ywYryIuw2yLoA41fq8KV+IgtPevB9U68gfYaOJom8Lx8Yxkf0V2BiVq3nDKqPw/5X/03zNLgb43iVzOww+0iDeGY1pfvjwUll9ppN3YNGoa/ep0QvbvtKWCciv+C+fC+tqvFtBq3YfCKUqLQcWTSCsWCjAt2tYMkMw5tiSxDgTCO0vNL9DXsDq24wge5dY4ju3tw0PYLXcuEfpKZh8OvoPwdchtteX7SVRfsUMi0S+z6q5GG5PkiQlfUja5ztneIy+E3xym+L4rD0HUJJvMFnPfGJboFxYqe+W7Tz8G84RKAnToR3lpPXU1Em62myycNzPptmS+zebKZVmYSr4qM2j3dKThlxAaaMidwyuxCslzwntAtREK7q2Xrd9HlgQ3diKDWCllteUDS3NdSE6YJMpeK0mlg6OYkHFFI/4Swbh8q7NbKXDHWzIu9JiTgrGWhC9rS97uvQj44sYXAY0qfr3SZU=
